dist: xenial
language: python
python:
- 3.6.9
- '3.7'
install:
- pip install -r requirements.txt
script:
- "/bin/bash -c ci/run.sh"
deploy:
  provider: pypi
  user: __token__
  password:
    secure: QCHI1FCs4GdJX/qR8Q1ErfAF2gnY+JkJAmwsIpflbf791/EePzR13JaqdymCDGELyiy/H6cEXKpBcl6OcZ/AzzZXGAjPguoe9LrieDBldTRzRSYMuS2rGXReB7HGccb0oYe4w6+3bNNTK3x0MPe8/FTbulf5z2i9nBNAkBNkz4GtdcVJS8xXQ3QDGURYzmxIM22lITmvf0a2QIwRobwdEKjSTK7OPk4ZXl9fedwgcP88SD1jlRSq/lY6dBA+zkfAP+PCpIEsJsEcwkLxYTKYTrwdeKvKuH2gWs1r8Iamn9wJLVVPOikuWhbblGhofO0mvO3oTnKAN2Wnd3fWngMddo8PES7UU0xV7dQShSQB6iVDh9xq165XG9owPUBrME4xqNg8q70c29Wtk/aybSTlQmCe4ijseLPeSy1PcM+ebCiDlmjErsR4QOJGJQHZGchUzNZ4HxQ8cq9YBQ7cK2hD8ssXnhYLaG4bzZqV2APlmRaSpL/siXBUZmmPl9DpLJiYwZjgr3Zs2PJXUiOc2FlNBxpz7+SmzkeLoDyNB49ZYqEdbdxn2Xe+dcsoXs+wFFBbcVjW5vh+6j4g5e4n2XsgEylErP/3tGB21tvzlPLqyE0cefJwOXqvhxOystJoq00hE8D3aIUqaV36JAIUUZfMtHv8XfpxAQWUoXJtsqQrz84=
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
